name: flutter-codemagic-example
version: git
summary: Flutter Codemagic Example
description: Flutter Codemagic Example that does everything!
confinement: strict
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

apps:
  flutter-codemagic-example:
    command: flutter_codemagic_example
<<<<<<< HEAD
    extensions: [flutter-master]
=======
    extensions: [flutter-stable]
>>>>>>> 3595bd5ba09b7d3d0c111b4b7b7d3936c20b3382

parts:
  flutter-codemagic-example:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
